### ISSUE TITLE
Co-op Vault Issue

### ISSUE THREAD

**Issue by Orthus** [nodecraft/customer-suggestions#6] opened 2015-10-16 19:38 UTC
Customer unable to specify max payment. This is likely an internal issue with passing the entered value to the database.

**Comment by blazedd** [comment] 2015-12-11 18:57
The problem is that we were using the `type="number"` which collides with the `money` directive as per  https://github.com/fiestah/angular-money-directive/issues/8

Now resolved with `type="input"`

**Closed by blazedd** 2015-12-11 18:57 UTC
Labels: implemented
